# Generated by Django 5.1.1 on 2024-11-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productCategory',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
