# Generated by Django 5.1.3 on 2024-12-28 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0002_remove_user_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddresses',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userAddresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
