# Generated by Django 5.1.1 on 2024-11-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0003_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
