# Generated by Django 5.1.1 on 2024-11-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0004_alter_products_price_alter_products_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='numReviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='stockCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
