# Generated by Django 5.1.1 on 2024-11-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0005_products_numreviews_alter_products_stockcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='productCategory',
        ),
        migrations.AddField(
            model_name='products',
            name='productCategories',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
