# Generated by Django 5.1.3 on 2025-01-17 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='productReviews',
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productReviews', to='appMain.products'),
        ),
    ]
