# Generated by Django 5.1.1 on 2024-11-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0008_remove_products_productcategories_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='productReviews',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='productSpecification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
