# Generated by Django 5.1.1 on 2024-11-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0009_products_productdescription_products_productreviews_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='productInfo',
            new_name='productInformation',
        ),
    ]
