# Generated by Django 5.1.3 on 2025-03-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0009_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
