# Generated by Django 5.1.1 on 2024-11-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0010_rename_productinfo_products_productinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='productInformation',
        ),
    ]
