# Generated by Django 5.1.3 on 2024-12-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0011_remove_products_productinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='productSpecification',
            new_name='productSpecifications',
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
