# Generated by Django 5.1.3 on 2024-12-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0012_rename_productspecification_products_productspecifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True),
        ),
    ]
