# Generated by Django 5.1.3 on 2024-12-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0013_alter_products_image_alter_products_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='numReviews',
            new_name='productNumReviews',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='stockCount',
            new_name='productStockCount',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rating',
        ),
        migrations.AddField(
            model_name='products',
            name='productPrice',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='productRating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
