# Generated by Django 5.1.3 on 2024-12-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0014_rename_numreviews_products_productnumreviews_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='productImage',
        ),
    ]
