# Generated by Django 5.1.3 on 2024-12-24 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0015_rename_image_products_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='productImage',
        ),
        migrations.AddField(
            model_name='products',
            name='productImageAttr1',
            field=models.ImageField(blank=True, null=True, upload_to='products/attr/'),
        ),
        migrations.AddField(
            model_name='products',
            name='productImageAttr2',
            field=models.ImageField(blank=True, null=True, upload_to='products/attr/'),
        ),
        migrations.AddField(
            model_name='products',
            name='productImageMain',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/'),
        ),
        migrations.AddField(
            model_name='products',
            name='productImageMeasurements1',
            field=models.ImageField(blank=True, null=True, upload_to='products/measurements/'),
        ),
        migrations.AddField(
            model_name='products',
            name='productImageMeasurements2',
            field=models.ImageField(blank=True, null=True, upload_to='products/measurements/'),
        ),
        migrations.AddField(
            model_name='products',
            name='productImageTheme',
            field=models.ImageField(blank=True, null=True, upload_to='products/theme/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
