# Generated by Django 5.1.3 on 2024-12-24 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0016_remove_products_productimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='productImageAttr1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='productImageAttr2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='productImageMain',
        ),
        migrations.RemoveField(
            model_name='products',
            name='productImageMeasurements1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='productImageMeasurements2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='productImageTheme',
        ),
        migrations.AddField(
            model_name='products',
            name='updatedAT',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('uploadedAT', models.DateTimeField(auto_now_add=True)),
                ('updatedAT', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='appMain.products')),
            ],
        ),
    ]
