# Generated by Django 5.1.3 on 2024-12-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0017_remove_products_productimageattr1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
