# Generated by Django 5.1.3 on 2024-12-27 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0018_alter_productimages_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImages', to='appMain.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='productBrand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='productName',
            field=models.CharField(max_length=255),
        ),
    ]
