export const ADMIN_ORDERS_REQUEST = "ADMIN_ORDERS_REQUEST";
export const ADMIN_ORDERS_SUCCESS = "ADMIN_ORDERS_SUCCESS";
export const ADMIN_ORDERS_FAIL = "ADMIN_ORDERS_FAIL";

export const ADMIN_ORDER_DETAILS_REQUEST = "ADMIN_ORDER_DETAILS_REQUEST";
export const ADMIN_ORDER_DETAILS_SUCCESS = "ADMIN_ORDER_DETAILS_SUCCESS";
export const ADMIN_ORDER_DETAILS_FAIL = "ADMIN_ORDER_DETAILS_FAIL";

export const ADMIN_ORDER_DISPATCH_REQUEST = "ADMIN_ORDER_DISPATCH_REQUEST";
export const ADMIN_ORDER_DISPATCH_SUCCESS = "ADMIN_ORDER_DISPATCH_SUCCESS";
export const ADMIN_ORDER_DISPATCH_FAIL = "ADMIN_ORDER_DISPATCH_FAIL";
