export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAIL = "USER_PROFILE_UPDATE_FAIL";

export const USER_ADDRESS_FETCH_REQUEST = "USER_ADDRESS_FETCH_REQUEST";
export const USER_ADDRESS_FETCH_SUCCESS = "USER_ADDRESS_FETCH_SUCCESS";
export const USER_ADDRESS_FETCH_FAIL = "USER_ADDRESS_FETCH_FAIL";

export const USER_ADDRESS_ADD_REQUEST = "USER_ADDRESS_ADD_REQUEST";
export const USER_ADDRESS_ADD_SUCCESS = "USER_ADDRESS_ADD_SUCCESS";
export const USER_ADDRESS_ADD_FAIL = "USER_ADDRESS_ADD_FAIL";

// export const USER_ADDRESS_EDIT_REQUEST = "USER_ADDRESS_EDIT_REQUEST";
// export const USER_ADDRESS_EDIT_SUCCESS = "USER_ADDRESS_EDIT_SUCCESS";
// export const USER_ADDRESS_EDIT_FAIL = "USER_ADDRESS_EDIT_FAIL";

export const USER_ADDRESS_DELETE_REQUEST = "USER_ADDRESS_DELETE_REQUEST";
export const USER_ADDRESS_DELETE_SUCCESS = "USER_ADDRESS_DELETE_SUCCESS";
export const USER_ADDRESS_DELETE_FAIL = "USER_ADDRESS_DELETE_FAIL";
