export const PRODUCT_REVIEWS_REQUEST = "PRODUCT_REVIEWS_REQUEST";
export const PRODUCT_REVIEWS_SUCCESS = "PRODUCT_REVIEWS_SUCCESS";
export const PRODUCT_REVIEWS_FAIL = "PRODUCT_REVIEWS_FAIL";

export const USER_REVIEWS_REQUEST = "USER_REVIEWS_REQUEST";
export const USER_REVIEWS_SUCCESS = "USER_REVIEWS_SUCCESS";
export const USER_REVIEWS_FAIL = "USER_REVIEWS_FAIL";

export const REVIEW_ADD_REQUEST = "REVIEW_ADD_REQUEST";
export const REVIEW_ADD_SUCCESS = "REVIEW_ADD_SUCCESS";
export const REVIEW_ADD_FAIL = "REVIEW_ADD_FAIL";

export const REVIEW_UPDATE_REQUEST = "REVIEW_UPDATE_REQUEST";
export const REVIEW_UPDATE_SUCCESS = "REVIEW_UPDATE_SUCCESS";
export const REVIEW_UPDATE_FAIL = "REVIEW_UPDATE_FAIL";

export const REVIEW_DELETE_REQUEST = "REVIEW_DELETE_REQUEST";
export const REVIEW_DELETE_SUCCESS = "REVIEW_DELETE_SUCCESS";
export const REVIEW_DELETE_FAIL = "REVIEW_DELETE_FAIL";
